### ISSUE TITLE
Migrate to OpenSlides 2.2

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-protocol#15]
OpenSlides 2.2 was released today! :tada: 

This plugin should migrate to OpenSlides 2.2 as well, add the necessary changes and add OpenSlides >= 2.2 as dependency.

**Comment by tsiegleauq** [comment]
The plugin dies not appear in the navbar in OpenSlides 2.2

**Comment by emanuelschuetze** [comment]
Done
