### ISSUE TITLE
hi = "ho" ?

### ISSUE THREAD

**Issue by tsiegleauq** [OpenSlides/openslides-protocol#9]
[openslides-protocol/blob/master/openslides_protocol/projector.py
](https://github.com/OpenSlides/openslides-protocol/blob/master/openslides_protocol/projector.py)
has a suspiciously small amount of (probably unnecessary?) content. Guess that has been mistakenly commited?

**Comment by emanuelschuetze** [comment]
@FinnStutzenstein Please check!

**Comment by FinnStutzenstein** [comment]
Not mistaken, but this is a leftover of the migration from OS 1 to OS 2. The intention was: "Maybe I need this file, write something in it" ;)

The PR is OK!
